name: fakeflix

services:
  db:
    image: postgres:15-alpine
    container_name: fakeflix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fakeflix
    ports:
      - "5433:5432"
    volumes:
      - .data:/var/lib/postgresql/data

